programs:

  ls:
    cmd: "/bin/ls -l"
    numprocs: 3
    umask: 022
    workingdir: .
    autostart: true
    autorestart: unexpected
    exitcodes:
    - 0
    - 2
    startretries: 0
    starttime: 0
    stopsignal: TERM
    stoptime: 1
    stdout: ./logs/ls.stdout
    stderr: ./logs/ls.stderr
    env:
      STARTED_BY: taskmaster
      ANSWER: 42

  sleep:
    cmd: "/bin/sleep 3"
    numprocs: 1
    umask: 022
    workingdir: .
    autostart: false
    autorestart: unexpected
    exitcodes:
    - 0
    startretries: 3
    starttime: 10
    stopsignal: USR1
    stoptime: 3
    stdout: ./logs/sleep.stdout
    stderr: ./logs/sleep.stderr
    env:
      STARTED_BY: taskmaster
      ANSWER: 42

  sleep3:
    cmd: "/bin/sleep 5"
    numprocs: 2
    umask: 022
    workingdir: .
    autostart: false
    autorestart: unexpected
    exitcodes:
    - 0
    startretries: 3
    starttime: 2
    stopsignal: USR1
    stoptime: 3
    stdout: ./logs/sleep.stdout
    stderr: ./logs/sleep.stderr
    env:
      STARTED_BY: taskmaster
      ANSWER: 42

  env:
    cmd: "/bin/env"
    numprocs: 3
    umask: 022
    workingdir: .
    autostart: false
    autorestart: unexpected
    exitcodes:
    - 0
    - 2
    startretries: 3
    starttime: 0
    stopsignal: TERM
    stoptime: 1
    stdout: ./logs/env.stdout
    stderr: ./logs/env.stderr
    env:
      STARTED_BY: taskmaster
      ANSWER: 42

  nginx:
    cmd: "/usr/local/bin/nginx -c /etc/nginx/test.conf"
    numprocs: 1
    umask: 022
    workingdir: /tmp
    autostart: true
    autorestart: unexpected
    exitcodes:
    - 0
    startretries: 1
    starttime: 5
    stopsignal: TERM
    stoptime: 10
    stdout: /tmp/nginx.stdout
    stderr: /tmp/nginx.stderr
    env:
      STARTED_BY: taskmaster
      ANSWER: 42

  # vogsphere:
  #   cmd: "/usr/local/bin/vogsphere-worker --no-prefork"
  #   numprocs: 8
  #   umask: 077
  #   workingdir: /tmp
  #   autostart: false
  #   autorestart: unexpected
  #   exitcodes: 0
  #   startretries: 3
  #   starttime: 5
  #   stopsignal: USR1
  #   stoptime: 10
  #   stdout: /tmp/vgsworker.stdout
  #   stderr: /tmp/vgsworker.stderr